import { Inter } from "next/font/google";
import "./../globals.css";
import Navbar from "../Components/Navbar";
import MyProfile from "../Components/MyProfile";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex main-container-height">
          <div className="w-1/5 border-r border-gray-300 main-container-height overflow-y-auto">
            <MyProfile />
          </div>
          <div className="w-4/5 main-container-height overflow-y-auto py-4 px-6">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
